### ISSUE TITLE
【开源自荐】用 GPT-Runner 管理您的 AI 预设，通过 AI 与您的代码文件聊天，极大提升您和团队的开发效率！

### ISSUE THREAD

**Issue by 2214962083** [EwingYangs/awesome-open-gpt#28]
Github: https://github.com/nicepkg/gpt-runner

<img width="1438" alt="Screenshot 2023-07-15 at 23 22 03" src="https://github.com/EwingYangs/awesome-open-gpt/assets/35005637/4d5cb660-64cf-4c44-93af-54c581e7c69c">

**Comment by EwingYangs** [comment]
已收录
