### ISSUE TITLE
【开源推荐】AI GitCommit Tools 

### ISSUE THREAD

**Issue by uk0** [EwingYangs/awesome-open-gpt#29]
hi bro 
我想推荐一个用openai api 提供 git commit 支持的一个小工具，目前还在更新中。
1. 推荐理由 使用简单，只有一个shell，很简单。
2. 可以自己修改提示词，更改插件。

地址 ： https://github.com/uk0/aicommit-shell

**Comment by EwingYangs** [comment]
好的，谢谢，我会考虑

**Comment by EwingYangs** [comment]
好的，谢谢，我会考虑
